[package]
name = "canopen_dev"
version = "0.1.0"
authors = ["nimrof"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
